package hb.xnwdw.com.wendangwang.Dao.DaoResponse;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import hb.xnwdw.com.wendangwang.Dao.DaoResponse.MessageDaoResponse;

import hb.xnwdw.com.wendangwang.Dao.DaoResponse.MessageDaoResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoResponseDaoConfig;

    private final MessageDaoResponseDao messageDaoResponseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoResponseDaoConfig = daoConfigMap.get(MessageDaoResponseDao.class).clone();
        messageDaoResponseDaoConfig.initIdentityScope(type);

        messageDaoResponseDao = new MessageDaoResponseDao(messageDaoResponseDaoConfig, this);

        registerDao(MessageDaoResponse.class, messageDaoResponseDao);
    }
    
    public void clear() {
        messageDaoResponseDaoConfig.clearIdentityScope();
    }

    public MessageDaoResponseDao getMessageDaoResponseDao() {
        return messageDaoResponseDao;
    }

}
