package hb.xnwdw.com.wendangwang.Dao.DaoResponse;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE_DAO_RESPONSE".
*/
public class MessageDaoResponseDao extends AbstractDao<MessageDaoResponse, Long> {

    public static final String TABLENAME = "MESSAGE_DAO_RESPONSE";

    /**
     * Properties of entity MessageDaoResponse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property MessageCount = new Property(1, String.class, "messageCount", false, "MESSAGE_COUNT");
    }


    public MessageDaoResponseDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDaoResponseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE_DAO_RESPONSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"MESSAGE_COUNT\" TEXT);"); // 1: messageCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE_DAO_RESPONSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MessageDaoResponse entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String messageCount = entity.getMessageCount();
        if (messageCount != null) {
            stmt.bindString(2, messageCount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MessageDaoResponse entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String messageCount = entity.getMessageCount();
        if (messageCount != null) {
            stmt.bindString(2, messageCount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public MessageDaoResponse readEntity(Cursor cursor, int offset) {
        MessageDaoResponse entity = new MessageDaoResponse( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // messageCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MessageDaoResponse entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setMessageCount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MessageDaoResponse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MessageDaoResponse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MessageDaoResponse entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
